# Grant KCC owner of this project
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kcc-project-id-owners-permissions # {"$kpt-set":"project-id-sa-owners-permissions"}
  namespace: projects # {"$kpt-set":"projects-namespace"}
  annotations:
    cnrm.cloud.google.com/project-id: management-project-id # {"$kpt-set":"management-project-id"}
spec:
  member: "serviceAccount:kcc-project-id@management-project-id.iam.gserviceaccount.com" # {"$kpt-set":"project-id-sa-ref"}
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: project-id # {"$kpt-set":"project-id"}
