# Create namespace in the Config Controller cluster to manage KCC resources in this project
apiVersion: v1
kind: Namespace
metadata:
  name: project-id # {"$kpt-set":"project-namespace"}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # {"$kpt-set":"project-id"}
