apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: network-1-router-nat # kpt-set: ${prefix}${network-name}-router-nat
  namespace: networking # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  natIpAllocateOption: AUTO_ONLY
  region: us-west1 # kpt-set: ${region}
  routerRef:
    name: network-1-router # kpt-set: ${prefix}${network-name}-router
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES # kpt-set: ${source-subnetwork-ip-ranges-to-nat}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  name: network-1-router # kpt-set: ${prefix}${network-name}-router
  namespace: networking # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: project-id # kpt-set: ${project-id}
spec:
  description: example router description
  networkRef:
    name: network-1 # kpt-set: ${network-name}
  region: us-west1 # kpt-set: ${region}
