apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: public-ip
  namespace: config-control
  labels:
    label-one: "public-ip"
  annotations:
    cnrm.cloud.google.com/project-id: yourproject # kpt-set: ${project-id}
spec:
  addressType: EXTERNAL
  description: public IP for LB
  location: region # kpt-set: ${region}
  ipVersion: IPV4
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: forwardingrule
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: yourproject # kpt-set: ${project-id}
spec:
  description: "Forwarding Rule for Autoscale Group"
  loadBalancingScheme: EXTERNAL
  portRange: "1-65535"
  ipProtocol: "TCP"
  ipVersion: "IPV4"
  location: us-west1  # kpt-set: ${region}
  target:
    name: target-pool
  ipAddress:
    addressRef:
      name: public-ip
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetPool
metadata:
  name: target-pool
  namespace: config-control # kpt-set: ${namespace}
  labels:
    label-one: "target-pool"
  annotations:
    cnrm.cloud.google.com/project-id: yourproject # kpt-set: ${project-id}
spec:
  description: Target Pool
  healthChecks:
    - httpHealthCheckRef:
        name: computetargetpool-hc
  region: us-west1 # kpt-set: ${region}
  sessionAffinity: CLIENT_IP
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHTTPHealthCheck
metadata:
  name: computetargetpool-hc
  namespace: config-control # kpt-set: ${namespace}
  labels:
    label-one: "lb-health-check"
  annotations:
    cnrm.cloud.google.com/project-id: yourproject # kpt-set: ${project-id}
spec:
  checkIntervalSec: 10
  description: example HTTP health check
  healthyThreshold: 2
  port: 40000
  requestPath: /
  timeoutSec: 5
  unhealthyThreshold: 2