apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: network-1-fw-allow-gcp-lb # kpt-set: ${network-name}-fw-allow-gcp-lb
  namespace: firewalls-namespace # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/project-id: yourproject # kpt-set: ${project-id}
spec:
  priority: 10000 # kpt-set: ${priority}
  allow:
    - ports:
        - "80"
        - "443"
        - "8080"
      protocol: tcp
  direction: INGRESS
  disabled: false
  enableLogging: false # kpt-set: ${enable-logging}
  networkRef:
    external: projects/your-project/global/networks/your-network # kpt-set: projects/${project-id}/global/networks/${network-name}
    #name: network-1 # kpt-set: ${network-name}
  sourceRanges:
    - "35.191.0.0/16"
    - "130.211.0.0/22"
    - "209.85.152.0/22"
    - "209.85.204.0/22"
  targetTags:
    - allow-gcp-lb
