apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
  name: blueprints-project-bigip-instance # {"$ref":"#/definitions/io.k8s.cli.substitutions.bigip-name"}
  labels:
    created-from: "image"
    network-type: "subnetwork"
spec:
  machineType: n1-standard-4
  zone: us-west1-a
  bootDisk:
    initializeParams:
      #size: 24
      type: pd-ssd
      sourceImageRef:
        external: projects/f5-7626-networks-public/global/images/f5-bigip-16-0-1-1-0-0-6-payg-best-25mbps-210129040615
  networkInterface:
    - subnetworkRef:
        name: cf-network-management-subnet-us-west1
      # aliasIpRange:
      #   - ipCidrRange: /24
      #     subnetworkRangeName: cloudrange
  minCpuPlatform: "Intel Skylake"
  metadataStartupScript: "!/bin/bash\n echo hello > /config/test-script.txt"
  serviceAccount:
    serviceAccountRef:
      name: blueprint-bigip-service-account
    scopes:
    - compute-rw
    - logging-write
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: blueprint-bigip-service-account

