apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: blueprints-project-bigip-bucket # {"$ref":"#/definitions/io.k8s.cli.substitutions.bigip-name"}
  namespace: config-control # {"$kpt-set":"namespace"}
  annotations:
    cnrm.cloud.google.com/project-id: blueprints-project # {"$kpt-set":"project-id"}
    cnrm.cloud.google.com/force-destroy: "false"
spec:
  storageClass: standard # {"$kpt-set":"storage-class"}
  uniformBucketLevelAccess: true
  versioning:
    enabled: false
