apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: bigip-demo
  namespace: config-control
  labels:
    created-from: image
    network-type: subnetwork
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
    cnrm.cloud.google.com/project-id: yourproject # kpt-set: ${project-id}
spec:
  serviceAccount:
    scopes:
      - cloud-platform
    serviceAccountRef:
      name: bigip-srvacct
  bootDisk:
    initializeParams:
      #size: 24
      type: pd-ssd
      sourceImageRef:
        external: projects/f5-7626-networks-public/global/images/f5-bigip-16-0-1-1-0-0-6-payg-best-25mbps-210129040615
  machineType: n1-standard-4
  metadataStartupScript: |-
    #!/bin/bash
     echo hello > /config/test-script.txt
  minCpuPlatform: Intel Skylake
  networkInterface:
    - subnetworkRef:
        external: projects/your-project/regions/us-west1/subnetworks/your-subnet-us-west1 # kpt-set: projects/${project-id}/regions/${region}/subnetworks/${subnetwork}
      networkIp: 10.0.11.80
  zone: us-west1-a